### ISSUE TITLE
wrong font is used inside <b> and <i> tags

### ISSUE THREAD

**Issue by Ivan31415** [dhorions/boxable#125] opened 2017-10-13 09:59 UTC
```
PDFont font = PDType0Font.load(document, new File("Times New Roman Cyr Regular.TTF"));

...
Cell<PDPage> cell = row.createCell(100, "Regular text - correct font. <b>Bold font - wrong font. </b><i>Italic font - wrong font.</i> ");
cell.setFont(font);
...
```

expected result
all font in cell is Times New Roman
actual result
only regular text is Times New Roman
![cell](https://user-images.githubusercontent.com/3274825/31541105-4788ceb6-b016-11e7-8c6f-0c388bb002ca.png)

Please provide an ability to specify bold and italic font to be used in cell

**Comment by flurinBoonea** [comment] 2017-10-13 09:59
Your email was received, checked for viruses and our AI realized that it has great content, is well written and deserves a considerate and well thought out answer.

BUT:

I am currently not in the office and will reply to your email upon my return on the 16th of October 2017.

Ich bin zur Zeit nicht im Büro und werde nach meiner Rückkehr am 16. Oktober 2017 antworten.

Flurin Capaul

**Comment by Frulenzo** [comment] 2017-11-06 13:36
You will need Times New Roman normal, italic, bold and italic + bold 👍 

I suggest you to use `FontUtils.addDefaultFonts()` method which will provide you the functionality that you need.

**Comment by czyzmichal** [comment] 2017-11-06 15:26
I have the same problem, but method `FontUtils.addDefaultFonts()` doesn't exist yet.

**Comment by Frulenzo** [comment] 2017-11-06 20:35
Oh, you are right. I implemented that in SZUE/boxable. Sometimes I mixed "official" boxable and my forked boxable.

**Comment by dhorions** [comment] 2017-11-06 20:53
@Frulenzo Hey, since your are currently the main contributer to this project, maybe you should do a pull request with all the improvements you added and release a new version.
Can you contact me if you're interested?

Thanks, 

Dries

**Comment by Frulenzo** [comment] 2017-11-07 09:13
Yeah, I would like to do that. But let me first cross check SZUE/boxable with this official version so I really know what is implented and where 😄 After that I will make big PR and then we could defintely make new release

**Comment by Frulenzo** [comment] 2017-11-07 10:25
@dhorions 
Can you maybe make **organization** for this boxable project and make me as organization member? That allows me to make possible CI with travis etc.

**Comment by dhorions** [comment] 2017-11-07 10:55
Hi,
I have never transferred a repo to an organization.  Do you know what will happen with the original repository?

**Comment by Frulenzo** [comment] 2017-11-07 12:31
Hmm, if I read correctly -> https://help.github.com/articles/about-repository-transfers/#whats-transferred-with-a-repository

We are pretty safe with all points but I am not sure what happens with maven :/ I need to read more about it. Wait a little bit with this tranfer. Momentarily it is not essential.

**Comment by dhorions** [comment] 2017-12-05 10:57
@Frulenzo How are we going to proceed?  I'd really like you to be able to release the next versions with all the improvements and bugfixes you worked on.

**Comment by Frulenzo** [comment] 2017-12-05 13:06
I should cherry pick all relevent commits from SZUE/Boxable [(LINK)](https://github.com/SZUE/boxable) and make a big PULL request. The problem is always: **time**. It is a little bit hectic on work and I really don't have much spare time on my hands :/

**Closed** 2018-02-08 09:32 UTC
